project:
  type: website

website:
  title: "matriz_wiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Problem-identification-tools.qmd
        text: Problem-identification
      - href: Problem-solving-tools.qmd
        text: Problem-solving
      - href: Concept-substantiation-tools.qmd
        text: Concept-substantiation
      - href: TESE.qmd
        text: TESE

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual