## GLOSSARY

# GLOSSARY

*This following glossary provides key definitions aligned with the MATRIZ methodology.*

*Each term includes a link to an article with more detailed information on the topic.*

## A

**Additional function**: a useful function that acts on a component of the supersystem that is not a target component.

**Algorithm for resolving physical contradictions**: a problem-solving tool that provides a systematic access to the inventive principles for solving physical contradictions.

**Alternative system**: a competing system that has a complementary, to the base system, pair of advantages and disadvantages.

**Altshuller matrix:** *go to* contradiction matrix.

**ARIZ**: a problem-solving tool that transforms a complex key problem into a well-defined model of the problem, which can be solved effectively using a wide spectrum of TRIZ tools.

**Auxiliary function**: a useful function that acts on a component of the analyzed engineering system.

## B

**Base system:** a system to which features from the alternative system is transferred. The base system is the alternative system selected for improvement.

**Basic function**: a useful function directed toward a target component of the analyzed engineering system.

## C

**Cause – effect chain analysis (CECA):** an analytical tool that identifies the key disadvantages of the engineering system. This is accomplished by building cause-effect chains of disadvantages that link the initial disadvantage with its fundamental causes.

**Chain Su-Field**: a combination of two or more Su-Fields where one substance participates in two Su-Fields.

**Clone problems application**: a problem- solving tool that generalizes the approach to solving one problem and applies the approach to solving another problem.

**Competing system**: an engineering system that performs the same or similar main function as the analyzed system.

**Complex Su-Field**: a complete Su-Field with an extra substance (often in the form of an additive) that readily responds to the existing field.

**Component**: a material object that constitutes a part of an engineering system or its supersystem.

**Component analysis**: a stage in Function Analysis that identifies components of the engineering system and its supersystem.

**Component model**: a set of components belonging to the analyzed engineering system and its supersystem.

**Conflicting pair**: (in ARIZ) a pair of components, the tool(s) and the product(s), interaction between which causes a conflict that prevents reaching the required result.

**Contradiction matrix** (Altshuller matrix)**:** a matrix that provides a systematic access to the inventive principles for solving engineering contradictions.

**Corrective function**: a useful function that eliminates a defect.

**Cost analysis**: a step in function-cost analysis that identifies the absolute and relative costs of components that constitute a engineering system being analyzed.

## D

**Database of scientific effects**: a problem-solving tool used to solve key problems, modeled as functions. It is a collection of effects and scientific phenomena from various fields (physics, chemistry, biology, etc.), organized in accordance with a function-oriented and resource-oriented taxonomy (rather than topics).

**Defect**: a material object (a substance or a field) that impairs performance of a useful function or performs some harmful function.

**Double Su-Field**: a Su-Field where two different fields provide interactions between the substances (one substance acts on the second substance with two fields).

## E

**Engineering contradiction** (EC), also called **technical contradictions** (TC): a parametric model of the problem in which an attempt to improve one parameter of the engineering system leads to worsening of another parameter.

**Engineering system** (technical system): a system that has been developed to perform a function.

## F

**Feature transfer**: an analytical tool for improvement of an engineering system given (base system) by transferring certain features from the alternative system with the aim to combine the useful features in a single system.

**Feature transfer problem**: a key problem that must be resolved to realize feature transfer.

**Field**: an object without a rest mass that transfers interaction between substances.

**Flow:** a movement of substance, energy (field), and information within an engineering system.

**Flow analysis**: an analytical tool that identifies disadvantages in flows of energy, substances, and information in an engineering system.

**Flow disadvantage**: a disadvantage of the analyzed engineering system identified during flow analysis.

**Function**: an action performed by one material object (function carrier) to change or maintain a parameter of another material object (object of the function).

**Function analysis** (*see also*: **function-cost analysis**): an analytical tool that identifies functions, their characteristics, and the cost of the system and its supersystem components.

**Function–cost diagram**: the graph that presents function point score (*F*) of the system components against their cost (*C*).

**Function disadvantage**: a disadvantage of an engineering system identified during the function modeling.

**Function model**: a model of an engineering system that identifies and describes functions performed by the components of the system and its supersystem, their usefulness and performance level, and costs.

**Function modeling**: the stage in function analysis, during which a function model of the analyzed engineering system is built.

**Function-oriented search** (FOS): a problem-solving tool based upon identifying existing technologies worldwide, using function criteria.

**Function rank**: a dimensionless measure that determines the importance of the useful function.

**Functionality**: *go to* functionality index.

**Functionality index** (functionality): a dimensionless measure of the overall functional contribution of the component to the overall performance of the engineering system.

## H

**Harmful flow**: a flow whose object (substance, energy, or information) performs a harmful function.

**Harmful function**: a function performed by a function carrier that results in an inacceptable change or inacceptable preservation of a parameter of an object of the function.

**Harmful Su-Field**: a Su-Field which represents a model of a problem, in which at least one interaction is harmful or excessive (excessive = normal + harmful excess).

## I

**Ideal final result (IFR)**: a model of the best solution to an inventive problem, whereby the problem is fully eliminated with minimal changes to the system and without any deterioration of system parameters.

**Ideal system**: a system with infinite value. It may have no components or associated costs, but still deliver the intended functionality; in other words – it may not exist, but its main function is still being performed.

**Ideality**: the ratio of the total benefits provided by the system to the sum of all payment factors associated with it. Payment factors include not only direct costs but also required space, environmental damage, maintenance, etc.

**Incomplete Su-Field:** a Su-Field representing a model of a problem of lacking one substance, or a field, or substance and a field.

**Inert system**: *go to* neutral system.

**Initial disadvantage**: a disadvantage in the analyzed engineering system, the elimination of which is the goal of a project. The initial disadvantage is formulated as an inverted project goal.

**Innovative benchmarking**: an analytical tool that identifies the best engineering system for improvement and engineering system candidates for feature transfer.

**Insufficient Su-Field:** a Su-Field representing a problem model, which is complete but does not work.

**Interaction**: a physical touch between components of the engineeging system and/or components of its supersystem.

**Interaction analysis**: a stage of function analysis of devices that identifies interactions between the components included into the component model.

**Interaction matrix**: a table showing interactions among components of the analyzed engineering system and its supersystem. It is result of the interaction analysis.

**Inventive principle**: an abstract model of a solution that provides generalized recommendations for modifying the system to solve the problem formulated as the contradiction.

## K

**Key disadvantage**: a disadvantage selected to be eliminated to achieve the goal of the project. Usually, key disadvantages appear at the root of cause-effect chains.

**Key problem:** a problem that has been selected for solving to achieve the goal of the project.

## M

**Main function**: the function for which the engineering system was designed.

**Main parameter of value (MPV)**: a key attribute, parameter, or feature of a product that is important for the purchasing decision.

**MATChEM**: an acronym representing six types of fields used in TRIZ – mechanical, acoustic, thermal, chemical, electrical, and magnetic. The last two letters (EM) also stand for electromagnetic.

**Measurement function**: a useful function that reveals information about components.

**Measurement Su-Field**: a special type of a Su-Field which is used to present models of inventive problems where measurement or detection is required in terms of substance-field analysis. Its uniqueness lies in the fact that it is the only model with 2 fields and 1 substance (input field > substance > output field).

**Mini-problem**: a problem whose solution is limited by constraints against significant changes to the analyzed engineering system.

## N

**Neutral flow**: a flow that has an irrelevant or insignificant influence on the engineering system.

**Neutral system (inert system)**: a system that does not have the disadvantage of the base system (it is its advantage), but it also does not perform the desired main function (does not work) that is considered to be its disadvantage.

## O

**Operating time**: (in ARIZ) a time interval, when one of the contradiction requirements must be met.

**Operating zone**: (in ARIZ) a physical space, where one of the contradiction requirements must be met.

**Operation**: a set of functions within a technological process grouped because of certain considerations.

## P

**Partial trimming**: redistributing some useful functions of a system component to other components, while leaving the component in the system for performing remaining functions.

**Physical contradiction**: a parametric model of the problem that emerges when two justified contradictory demands are placed upon a single parameter of an object to provide the required result.

**Product**: (in ARIZ) the element that needs to be processed (manufactured, moved, changed, improved, protected from a harmful influence, revealed, measured etc.) according to the problem conditions

**Productive function**: a useful function that irreversibly (permanently) changes a parameter of its object.

**Providing function**: a useful function that is necessary for the performance of another useful function.

## S

**S-curve**: an S-shaped curve that represents the typical dependence of a main parameter of value of an evolving engineering system on time

**S-curve analysis**: an analytical tool based on the trend of S-curve evolution that determines where an engineering system is in its development and what steps should be taken to improve it.

**Standard inventive solutions (SIS)**: a set of 76 typical solution models, to typical problem models that are expressed in the form of substance-field (Su-Field) models.

**Substance**: an object with a rest mass.

**Substance-field analysis**: a part of standard inventive solutions application that models a problem in the form of a substance-fields model.

**Substance-field model (Su-Field model, Su-Field)**: an abstract model of a problem and potential solutions (when possible) formulated in terms of interactions between substances and fields.

**Supersystem**: a system that contains the analyzed engineering system as a component.

**Supporting function**: a useful function that temporarily changes a parameter of the product.

## T

**Target component**: an object of the main function of the engineering system.

**Technical contradiction**: *go to* [engineering contradiction](#d).

**Technical system**: *go to* [engineering system](#d).

**Technological process**: a process that uses material objects, such as raw material, labour, energy, and machinery, to create finished products.

**Theory of inventive problems solving, TRIZ** (ru: *теория решения изобретательских задач*): a discipline of applied sciences that deals with directions of development and methods for improvement of engineering systems.

**Tool**: (in ARIZ) an object directly interacting (conflicting) with the product in contradictions identified in part 1 of ARIZ.

**Transport function**: a useful function that changes a position of its object in space.

**Trend of decreasing human involvement**: trend of engineering system evolution according to which as an engineering system evolves, the number of engineering system functions performed by humans decreases.

**Trend of flow enhancement**: trend of engineering system evolution according to which as an engineering system evolves, flow rates of substances, energy, or information increase, and/or the flows are better utilized.

**Trend of increasing completeness of system components**: a trend of engineering system evolution according to which as an engineering system evolves, it acquires the following typical function blocks: operating agent, transmission, energy source, and control system.

**Trend of increasing controllability**: trend of engineering system evolution according to which as engineering systems evolve, they develop more ways in which they can be controlled.

**Trend of increasing coordination**: trend of engineering system evolution according to which as an engineering system evolves, characteristics of the components of the engineering system become more coordinated with each other and with the supersystem.

**Trend of increasing degree of trimming**: trend of engineering system evolution according to which as an engineering system evolves, system elements (components or operations) are eliminated without impairing the functionality of the system, and possibly improving it.

**Trend of increasing dynamization**: a trend of engineering system evolution according to which the engineering system and its components evolve towards becoming more flexible, dynamic, and adaptable – having more degrees of freedom.

**Trend of increasing value**: a trend of engineering system evolution according to which as an engineering system evolves its value always increases.

**Trend of S-curve evolution**: a trend of engineering system evolution located at the top position in the trends hierarchy. According to it, as an engineering system evolves, the evolution of each main parameter of value (MPV) describes an S-shaped curve in time.

**Trend of transition to supersystem**: a trend of engineering system evolution which states that as an engineering system evolves, it is integrated with supersystem components.

**Trend of uneven development of system components**: trend of engineering system evolution according to which as an engineering system evolves, development is concentrated on the operating agent first, and on the rest of the system later.

**Trends of engineering system evolution** (TESE): statistically proven or empirically derived directions of engineering system development that describe the natural transition of engineering systems from one state to another.

**Trimming**: an analytical tool for improving an engineering system by removing (trimming) certain components and redistributing their useful functions among the remaining system or its supersystem components, while preserving quality and performance of the system.

**Trimming model**: a function model of an improved engineering system developed through trimming.

**Trimming problem**: a problem that must be resolved to realize the trimming model.

**Trimming rule**: an option for eliminating a component of an engineering system by either eliminating its useful functions or redistributing them to other system or supersystem components.

**Typical parameters**: a limited set of the pre-defined generalized parameters that typically need improvement in the engineering system, used in the contradiction (Altshuller) matrix.

## U

**Useful flow**: a flow whose object (substance, energy, or information) performs a useful function or is an object of a useful function.

**Useful function**: a function performed by a function carrier that results in a positive (required) change or preservation a parameter of an object of the function.

## V

**Value**: the ratio of a normalized sum of component/system function points over the sum of its costs.

**Value analysis**: an analytical tool that compares relative functionality and relative cost of the system components.

**Vicious circle**: a situation in CECA when a disadvantage causes new disadvantages that lead to the original disadvantage to occur again.

## W

**Wasted flow**: a flow that is characterized by losses of substance, energy, or information.

## X

**X-factor**: (in ARIZ) any change in the engineering system (e.g., change in its components, parameters, etc.) that should be incorporated into the system in order to solve a problem.
